# Simple Cloud Build configuration for Next.js application
# This configuration only builds the application without creating Docker images
# Usage: gcloud builds submit --config cloudbuild-simple.yaml .

steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
  
  # Run linter (allow to fail - there are pre-existing lint issues)
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'lint']
    allowFailure: true
  
  # Build the Next.js application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

# Store the build output as artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/ulrm'
    paths: ['.next/**', 'public/**', 'package.json', 'next.config.js']

# Build timeout
timeout: '600s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
